spring:
  datasource:
    url: jdbc:mysql:///batch?useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
  batch:
    job:
      enabled: false
server:
  port: 80
  context-path: /task

logging:
  level:
    com.relic.mapper: debug